# SPDX-FileCopyrightText: Beñat Gartzia Arruabarrena <bgartzia@redhat.com>
#
# SPDX-License-Identifier: CC0-1.0

name: "Tests"
on:
  pull_request:
    branches:
      - "main"
permissions:
  contents: "read"

# Don't waste job slots on superseded code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  # Pinned toolchain for linting
  ACTIONS_LINTS_TOOLCHAIN: 1.85.0

jobs:
  tests-integration-just-stable:
    name: "Integration Tests, just"
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/confidential-clusters/buildroot:latest"
      options: "--privileged"
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v5
      - name: "Clone reference-values"
        uses: actions/checkout@v5
        with:
          repository: confidential-clusters/reference-values
          path: test-data
      - name: "Install toolchain"
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: "Cache build artifacts"
        uses: Swatinem/rust-cache@v2
      - name: "Run just tests"
        run: just -v $(just -l | grep -E "^ *test-.*$" | grep -v uki)
